In [25]:
import pandas as pd

In [26]:
data = pd.read_csv("s3://hwanawsbucket1/electricity_forecast_output/hwan_forecast_export_2022-04-20T05-38-11Z_part0.csv")

In [27]:
data

      item_id                  date        p10        p50        p90
0  client_339  2015-01-01T01:00:00Z  24.423128  28.176781  33.538437
1  client_339  2015-01-01T02:00:00Z  11.205835  16.806395  22.330692
2  client_339  2015-01-01T03:00:00Z   8.456601  14.201681  20.688839
3  client_339  2015-01-01T04:00:00Z  10.069338  15.803247  22.248055
4  client_339  2015-01-01T05:00:00Z   7.569178  14.942782  23.129631

# 여기서 부터

In [6]:
data1 = pd.read_csv("s3://hwanawsbucket1/electricity_forecast_output/*.csv")

In [7]:
data1

      item_id                  date        p10        p50        p90
0  client_339  2015-01-01T01:00:00Z  24.423128  28.176781  33.538437
1  client_339  2015-01-01T02:00:00Z  11.205835  16.806395  22.330692
2  client_339  2015-01-01T03:00:00Z   8.456601  14.201681  20.688839
3  client_339  2015-01-01T04:00:00Z  10.069338  15.803247  22.248055
4  client_339  2015-01-01T05:00:00Z   7.569178  14.942782  23.129631

In [28]:
results = []

for i in range(170):
    data1 = pd.read_csv("s3://hwanawsbucket1/electricity_forecast_output/hwan_forecast_export_2022-04-20T05-38-11Z_part{name}.csv".format(name=i))
    data = pd.concat([data, data1], axis = 0)

In [29]:
data

       item_id                  date        p10        p50        p90
0   client_339  2015-01-01T01:00:00Z  24.423128  28.176781  33.538437
1   client_339  2015-01-01T02:00:00Z  11.205835  16.806395  22.330692
2   client_339  2015-01-01T03:00:00Z   8.456601  14.201681  20.688839
3   client_339  2015-01-01T04:00:00Z  10.069338  15.803247  22.248055
4   client_339  2015-01-01T05:00:00Z   7.569178  14.942782  23.129631
..         ...                   ...        ...        ...        ...
25   client_94  2015-01-01T01:00:00Z   0.390023   2.404517   4.356125
26   client_94  2015-01-01T02:00:00Z  -0.371218   1.958351   3.577320
27   client_94  2015-01-01T03:00:00Z  -0.229984   1.427768   3.668395
28   client_94  2015-01-01T04:00:00Z  -1.218140   1.795216   5.085065
29   client_94  2015-01-01T05:00:00Z  -0.815566   2.242957   6.029601

[1855 rows x 5 columns]

In [ ]:
data.to_csv("electricity_forecast.csv")

# 여기 까지

In [30]:
data.iloc[1800:]

       item_id                  date         p10         p50         p90
10    client_8  2015-01-01T01:00:00Z   50.859292   58.661744   66.464196
11    client_8  2015-01-01T02:00:00Z   44.999660   54.361307   63.722954
12    client_8  2015-01-01T03:00:00Z   42.277628   53.034221   63.790814
13    client_8  2015-01-01T04:00:00Z   38.161570   49.969612   61.777654
14    client_8  2015-01-01T05:00:00Z   39.017455   52.032861   65.048267
0   client_279  2015-01-01T01:00:00Z   86.430817   94.706535  106.771172
1   client_279  2015-01-01T02:00:00Z   72.840363   87.363625  101.440086
2   client_279  2015-01-01T03:00:00Z   69.319908   81.866959   99.356781
3   client_279  2015-01-01T04:00:00Z   67.418144   82.584045  100.517014
4   client_279  2015-01-01T05:00:00Z   69.985588   83.681633   98.500374
0    client_32  2015-01-01T01:00:00Z   46.271080   50.122425   54.285854
1    client_32  2015-01-01T02:00:00Z   39.797947   45.114685   49.276283
2    client_32  2015-01-01T03:00:00Z   32.293064   37.796951   43.403938
3    client_32  2015-01-01T04:00:00Z   30.127712   35.108082   41.592941
4    client_32  2015-01-01T05:00:00Z   28.478079   33.961674   39.600842
5    client_65  2015-01-01T01:00:00Z   70.304581   75.476440   81.505020
6    client_65  2015-01-01T02:00:00Z   62.268673   67.243988   73.188171
7    client_65  2015-01-01T03:00:00Z   55.391140   60.054634   65.837914
8    client_65  2015-01-01T04:00:00Z   48.625549   54.442635   61.017097
9    client_65  2015-01-01T05:00:00Z   45.798866   51.111229   56.369175
0   client_366  2015-01-01T01:00:00Z  559.870383  634.861624  709.852864
1   client_366  2015-01-01T02:00:00Z  507.248300  594.483581  681.718863
2   client_366  2015-01-01T03:00:00Z  446.015235  543.975954  641.936673
3   client_366  2015-01-01T04:00:00Z  382.215723  489.838261  597.460799
4   client_366  2015-01-01T05:00:00Z  371.324673  487.810375  604.296077
0   client_102  2015-01-01T01:00:00Z  114.512243  201.230613  427.925406
1   client_102  2015-01-01T02:00:00Z   39.365644  158.893607  335.287449
2   client_102  2015-01-01T03:00:00Z   36.923300  126.164578  271.792327
3   client_102  2015-01-01T04:00:00Z   58.141340  149.208370  369.744258
4   client_102  2015-01-01T05:00:00Z   96.868217  184.906413  364.873129
5   client_211  2015-01-01T01:00:00Z  110.858609  134.443462  159.485082
6   client_211  2015-01-01T02:00:00Z   91.136998  118.628169  147.689975
7   client_211  2015-01-01T03:00:00Z   94.321660  120.531524  148.725859
8   client_211  2015-01-01T04:00:00Z  103.812928  133.732175  160.274736
9   client_211  2015-01-01T05:00:00Z  118.836182  151.506573  184.646040
10  client_245  2015-01-01T01:00:00Z  239.571900  287.321003  345.342791
11  client_245  2015-01-01T02:00:00Z  218.844998  280.106220  359.768975
12  client_245  2015-01-01T03:00:00Z  207.157661  255.738113  347.420649
13  client_245  2015-01-01T04:00:00Z  198.861176  253.630233  359.055006
14  client_245  2015-01-01T05:00:00Z  202.620230  267.532948  370.445071
15  client_285  2015-01-01T01:00:00Z   37.431574   48.284403   62.899435
16  client_285  2015-01-01T02:00:00Z   31.706371   47.255104   69.428196
17  client_285  2015-01-01T03:00:00Z   27.796113   40.162051   62.455737
18  client_285  2015-01-01T04:00:00Z   24.973836   38.481083   61.647858
19  client_285  2015-01-01T05:00:00Z   26.755558   42.379162   69.456269
20  client_325  2015-01-01T01:00:00Z   95.140297  106.059898  168.447601
21  client_325  2015-01-01T02:00:00Z   94.519997  108.862198  154.722595
22  client_325  2015-01-01T03:00:00Z   96.078598  115.414597  186.243805
23  client_325  2015-01-01T04:00:00Z   94.516800  108.556702  188.101593
24  client_325  2015-01-01T05:00:00Z   92.643402  110.735703  219.657104
25   client_94  2015-01-01T01:00:00Z    0.390023    2.404517    4.356125
26   client_94  2015-01-01T02:00:00Z   -0.371218    1.958351    3.577320
27   client_94  2015-01-01T03:00:00Z   -0.229984    1.427768    3.668395
28   client_94  2015-01-01T04:00:00Z   -1.218140    1.795216    5.085065
29   client_94  2015-01-01T05:00:00Z   -0.815566    2.242957    6.029601

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1855 entries, 0 to 29
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   item_id  1855 non-null   object
 1   date     1855 non-null   object
 2   p10      1855 non-null   float64
 3   p50      1855 non-null   float64
 4   p90      1855 non-null   float64
dtypes: float64(3), object(2)
memory usage: 87.0+ KB

In [36]:
data.to_csv("electricity_forecast.csv")

In [34]:
#pd.to_csv(data)
data.to_csv("s3://hwanawsbucket1/electricity_forecast.csv")

PermissionError: Access Denied

In [12]:
import glob
myFiles = glob.glob("s3://hwanawsbucket1/electricity_forecast_output/*.csv")

In [13]:
myFiles

[]

In [14]:
dfs = ()
for file in myFiles:
    df = pd.read_csv(file, index_col='lang')
    dfs = dfs + tuple((df,))

In [15]:
df = pd.concat(dfs,axis=0)

ValueError: No objects to concatenate